{% set name = "nanocetpy" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nanocetpy-{{ version }}.tar.gz
  sha256: 841f04ddce48709dc610dda0be9a2c599443c620f0fe4b3cb4ca6ef26f04ee79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6

test:
  imports:
    - nanocetpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Dispertech/NanoCETPy
  summary: NanoCET Control and Analysis Software
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - aquilesC
